# Generated by Django 5.0.7 on 2024-07-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='user',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
