# Generated by Django 5.0.7 on 2024-07-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_remove_user_direccion_alter_user_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='ubicacion_latitud',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='ubicacion_longitud',
        ),
        migrations.AddField(
            model_name='alerta',
            name='ubicacion',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
