# Generated by Django 5.0.7 on 2024-07-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0003_remove_alerta_ubicacion_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='titulo',
            field=models.CharField(choices=[('INUNDACION', 'Inundación'), ('INCENDIO', 'Incendio'), ('DESLIZAMIENTO', 'Deslizamiento')], max_length=200),
        ),
    ]
